package jp.hanatoya.ipcam.repo;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;
import org.greenrobot.greendao.annotation.OrderBy;
import org.greenrobot.greendao.annotation.ToMany;
import org.parceler.Parcel;

import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CAM".
 */
@Parcel
@Entity
public class Cam {

    @Id(autoincrement = true)
    Long id;

    @NotNull
    String type;

    @NotNull
    String name;

    @NotNull
    String host;

    @NotNull
    String protocol;
    int port;
    String username;
    String password;
    String node;
    Integer status;

    @ToMany(referencedJoinProperty = "camId")
    @OrderBy("id ASC")
    List<Switch> switches;

    @Generated
    public Cam() {
    }

    public Cam(Long id) {
        this.id = id;
    }

    @Generated
    public Cam(Long id, String type, String name, String host, String protocol, int port, String username, String password, String node, Integer status) {
        this.id = id;
        this.type = type;
        this.name = name;
        this.host = host;
        this.protocol = protocol;
        this.port = port;
        this.username = username;
        this.password = password;
        this.node = node;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getType() {
        return type;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setType(@NotNull String type) {
        this.type = type;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    @NotNull
    public String getHost() {
        return host;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setHost(@NotNull String host) {
        this.host = host;
    }

    @NotNull
    public String getProtocol() {
        return protocol;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setProtocol(@NotNull String protocol) {
        this.protocol = protocol;
    }

    public int getPort() {
        return port;
    }

    public void setPort(int port) {
        this.port = port;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getNode() {
        return node;
    }

    public void setNode(String node) {
        this.node = node;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }
    public List<Switch> getSwitches() {
        return switches;
    }

    public void setSwitches(List<Switch> switches) {
        this.switches = switches;
    }

}
